#!/usr/bin/expect -f

set timeout 20
set ip "193.203.160.3"
set user "s3t_dev"
set password "Travels2026#"

spawn ssh -o StrictHostKeyChecking=no $user@$ip

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "$ " {
        send "ls -l /home/s3t_dev/app_deploy/backend/TourBooking.Api/publish/TourBooking.Api.dll\r"
        expect "$ "
        send "exit\r"
    }
}

expect eof
