#!/usr/bin/expect -f

set timeout 20
set ip "193.203.160.3"
set user "s3t_dev"
set password "Travels2026#"

spawn ssh -o StrictHostKeyChecking=no $user@$ip

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "$ " {
        send "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"VMurugan@2025#SQL\" -d S3T_Production -Q \"SELECT name FROM sys.tables\" -W\r"
        expect "$ "
        send "exit\r"
    }
}

expect eof
