-- SQLite Migration Script for V2 Features

-- 1. Update Users Table
ALTER TABLE Users ADD COLUMN CompanyName TEXT DEFAULT '';
ALTER TABLE Users ADD COLUMN Address TEXT DEFAULT '';

-- 2. Update Vehicles Table
ALTER TABLE Vehicles ADD COLUMN IsDeleted INTEGER DEFAULT 0;
ALTER TABLE Vehicles ADD COLUMN Mileage REAL DEFAULT 0;

-- 3. Update Bookings Table
ALTER TABLE Bookings ADD COLUMN GroupBookingId TEXT NULL;
ALTER TABLE Bookings ADD COLUMN CustomerAddress TEXT NULL;
ALTER TABLE Bookings ADD COLUMN BaseRentAmount REAL DEFAULT 0;
ALTER TABLE Bookings ADD COLUMN MountainRent REAL DEFAULT 0;
ALTER TABLE Bookings ADD COLUMN DriverBatta REAL DEFAULT 0;
ALTER TABLE Bookings ADD COLUMN PermitCost REAL DEFAULT 0;
ALTER TABLE Bookings ADD COLUMN TollCost REAL DEFAULT 0;
ALTER TABLE Bookings ADD COLUMN OtherExpenses REAL DEFAULT 0;
ALTER TABLE Bookings ADD COLUMN DiscountAmount REAL DEFAULT 0;
ALTER TABLE Bookings ADD COLUMN Inclusions TEXT NULL;
ALTER TABLE Bookings ADD COLUMN Notes TEXT NULL;
ALTER TABLE Bookings ADD COLUMN ActualStartTime TEXT NULL;
ALTER TABLE Bookings ADD COLUMN ActualEndTime TEXT NULL;
ALTER TABLE Bookings ADD COLUMN StartKms INTEGER NULL;
ALTER TABLE Bookings ADD COLUMN EndKms INTEGER NULL;
ALTER TABLE Bookings ADD COLUMN DistanceKm INTEGER DEFAULT 0;
ALTER TABLE Bookings ADD COLUMN Rating INTEGER NULL;
ALTER TABLE Bookings ADD COLUMN Feedback TEXT NULL;
ALTER TABLE Bookings ADD COLUMN CurrentLat REAL NULL;
ALTER TABLE Bookings ADD COLUMN CurrentLng REAL NULL;
ALTER TABLE Bookings ADD COLUMN LastLocationUpdate TEXT NULL;
ALTER TABLE Bookings ADD COLUMN TrackingEnabled INTEGER DEFAULT 0;

-- 4. Create PaymentLogs Table
CREATE TABLE IF NOT EXISTS PaymentLogs (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    BookingId INTEGER NOT NULL,
    Amount REAL NOT NULL,
    PaymentDate TEXT NOT NULL,
    PaymentMode TEXT DEFAULT 'Cash',
    ReferenceNumber TEXT NULL,
    Notes TEXT NULL,
    CollectedBy TEXT DEFAULT '',
    FOREIGN KEY(BookingId) REFERENCES Bookings(Id) ON DELETE CASCADE
);

-- 5. Create FuelLogs Table
CREATE TABLE IF NOT EXISTS FuelLogs (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    BookingId INTEGER NOT NULL,
    Place TEXT DEFAULT '',
    Liters REAL NOT NULL,
    CostPerLiter REAL NOT NULL,
    TotalCost REAL NOT NULL,
    OdometerReading INTEGER NOT NULL,
    FilledAt TEXT NOT NULL,
    ReceiptImage TEXT NULL,
    FOREIGN KEY(BookingId) REFERENCES Bookings(Id) ON DELETE CASCADE
);
